// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXb-8UE19fJb-c3bsxogCEV-_2_Cqk9R8',
    appId: '1:724055817942:web:d4f364c4331c60d235d377',
    messagingSenderId: '724055817942',
    projectId: 'otpapp-ebe3e',
    authDomain: 'otpapp-ebe3e.firebaseapp.com',
    storageBucket: 'otpapp-ebe3e.appspot.com',
    measurementId: 'G-XB4MZLVCR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2aokTJNfAQlojFH27uYx6GiG97X-oi0s',
    appId: '1:724055817942:android:f24f49400742c68535d377',
    messagingSenderId: '724055817942',
    projectId: 'otpapp-ebe3e',
    storageBucket: 'otpapp-ebe3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOP2UUY4Y--2kaHAhsknYDsuyiATZIWQY',
    appId: '1:724055817942:ios:c459c3bd1c1d2b0035d377',
    messagingSenderId: '724055817942',
    projectId: 'otpapp-ebe3e',
    storageBucket: 'otpapp-ebe3e.appspot.com',
    iosBundleId: 'com.example.flut1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOP2UUY4Y--2kaHAhsknYDsuyiATZIWQY',
    appId: '1:724055817942:ios:01450e6f247f112d35d377',
    messagingSenderId: '724055817942',
    projectId: 'otpapp-ebe3e',
    storageBucket: 'otpapp-ebe3e.appspot.com',
    iosBundleId: 'com.example.flut1.RunnerTests',
  );
}
